apiVersion: apps/v1
kind: Deployment
metadata:
  name: el-keycloak
  labels:
    app: el-keycloak
spec:
  selector:
    matchLabels:
      app: el-keycloak
  template:
    metadata:
      labels:
        app: el-keycloak
    spec:
      containers:
        - name: el-keycloak
          image: quay.io/keycloak/keycloak:24.0.0
          args:
            - "start-dev"
            - "--import-realm"
          ports:
            - containerPort: 8080
          env:
            - name: KEYCLOAK_ADMIN
              value: admin
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: secret
            - name: KC_DB
              value: postgres
            - name: KC_DB_URL
              value: jdbc:postgresql://el-postgres/keycloak
            - name: KC_DB_SCHEMA
              value: public
            - name: KC_DB_USERNAME
              value: postgres
            - name: KC_DB_PASSWORD
              value: secret
            - name: KC_HTTP_PORT
              value: "8080"
            - name: KC_HOSTNAME_URL
              value: http://el-keycloak/auth
            - name: KC_HOSTNAME_ADMIN_URL
              value: http://el-keycloak/auth
            - name: KC_HOSTNAME_STRICT_BACKCHANNEL
              value: "true"
            - name: KC_HTTP_RELATIVE_PATH
              value: /auth/
            - name: KC_HTTP_ENABLED
              value: "true"
            - name: KC_HEALTH_ENABLED
              value: "true"
            - name: KC_METRICS_ENABLED
              value: "true"
#          startupProbe:
#            httpGet:
#              path: /realms/master
#              port: 8080
#            failureThreshold: 40
#            periodSeconds: 10
#          readinessProbe:
#            httpGet:
#              path: /realms/master
#              port: 8080
#            initialDelaySeconds: 5
#            periodSeconds: 10
          resources:
            requests:
              cpu: 100m
              memory: 350Mi
            limits:
              cpu: 500m
              memory: 750Mi
          volumeMounts:
            - name: el-keycloak-config-volume
              mountPath: /opt/keycloak/data/import/
      volumes:
        - name: el-keycloak-config-volume
          configMap:
            name: el-keycloak-config

---

apiVersion: v1
kind: Service
metadata:
  name: el-keycloak
  labels:
    app: el-keycloak
spec:
  type: ClusterIP
  selector:
    app: el-keycloak
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: keycloak-ingress
  labels:
    app: el-keycloak
spec:
  rules:
    - host: el-keycloak
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: el-keycloak
                port:
                  number: 80
