server:
  port: 9000

spring:
  application:
    name: edge-service
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
        - SaveSession
        - TokenRelay
      routes:
        - id: resource-server-route
          uri: ${RESOURCE_SERVER_URL:http://localhost:9100}
          predicates:
            - Path=/api/**
          filters:
            - StripPrefix=1
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: edge-service
            client-secret: WRdVtsZ1oaVboulVqsNfBPcE5rZoc4VF
            scope: openid,roles
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/keycloak101
  redis:
    connect-timeout: 2s
    host: localhost
    port: 6379
    timeout: 1s
  session:
    store-type: redis
    timeout: 10m
    redis:
      namespace: polar:edge

management:
  endpoints:
    web:
      exposure:
        include: gateway, health, info