services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: changemeinprod
    ports:
      - '5432:5432'
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: "redis:7.0"
    restart: always
    ports:
      - '6379:6379'

  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    command: start-dev --import-realm
    volumes:
      - ./keycloak:/opt/keycloak/data/import
    environment:
      - KEYCLOAK_ADMIN=user
      - KEYCLOAK_ADMIN_PASSWORD=password
    ports:
      - 8080:8080