server:
  port: 9100
spring:
  application:
    name: resource-server
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
  datasource:
    url: jdbc:postgresql://localhost:5432/resource_server
    username: postgres
    password: changemeinprod
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000/auth/realms/thainguyencoffee
error:
  handling:
    exception-logging: no_logging
    http-status-in-json-response: true
    full-stacktrace-http-statuses: 5xx
    log-levels:
      5xx: ERROR
digitalocean:
  spaces:
    endpoint: https://bookstore-bucket.sgp1.digitaloceanspaces.com
    access-key: DO00XXYJDDAPT9EXWVF8
    secret-key: ZY2YAo3WrW+Eq28oLYVW89mDwst//QLJyqiF4TMP+Vg
    bucket-name: bookstore-bucket
STRIPE_SECRET_KEY: sk_test_51PtPqOLcSSqgAPH9SPAVNGV3vMYll5CNIvCUHFT7RJWIPkHTHa9LySfuiswCMvYlbe5KwKavly4QV6rjJP2zVBoS00x6oNhWCR