apiVersion: v1
kind: Service
metadata:
  name: bff-service
  labels:
    app: bff-service
spec:
  type: ClusterIP
  selector:
    app: bff-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 7081