# Build
custom_build(
    ref = 'lms-service',
    command = '../gradlew bootBuildImage --imageName $EXPECTED_REF',
    deps = ['build.gradle', 'src']
)

# Deploy
k8s_yaml(kustomize('k8s'))

# Manage
k8s_resource('lms-service', port_forwards=['7084'])
