server:
  port: 9001

spring:
  application:
    name: bff
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
        - SaveSession
        - TokenRelay
      routes:
        - id: spa-route
          uri: ${SPA_URL:http://localhost:9200/spa}
          predicates:
            - Path=/spa/**
        - id: resource-server-route
          uri: ${RESOURCE_SERVER_URL:http://localhost:9100}
          predicates:
            - Path=/api/**
          filters:
            - StripPrefix=1
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/keycloak101
        registration:
          keycloak:
            client-id: edge-service
            client-secret: keycloak-secret
            scope: openid,roles