keycloak-server-url: http://localhost:8080
realm_name: e-learning-project
client_id: bff-service-confidential
client_secret: secret

server:
  port: 7084
  shutdown: graceful
  tomcat:
    threads:
      min-spare: 5
      max: 50
    keep-alive-timeout: 15s
    connection-timeout: 2s

spring:
  application:
    name: lms
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
  datasource:
    url: jdbc:postgresql://localhost:5432/lms
    username: postgres
    password: secret
    hikari:
      connection-timeout: 2000 #ms
      maximum-pool-size: 20
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/e-learning-project
  modulith:
    events:
      jdbc:
        schema-initialization:
          enabled: true
    republish-outstanding-events-on-restart: true

management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

error:
  handling:
    exception-logging: no_logging
    http-status-in-json-response: true
    full-stacktrace-http-statuses: 5xx
    log-levels:
      5xx: ERROR

STRIPE_SECRET_KEY: sk_test_51PtPqOLcSSqgAPH9SPAVNGV3vMYll5CNIvCUHFT7RJWIPkHTHa9LySfuiswCMvYlbe5KwKavly4QV6rjJP2zVBoS00x6oNhWCR
KEYSTORE_PASSWORD: secret
KEY_PASSWORD: secret
KEYSTORE_PATH: src/main/resources/keystore/lms.p12
KEYSTORE_TYPE: PKCS12
KEY_ALIAS: lms

s3:
  access-key: DO00XXYJDDAPT9EXWVF8
  secret-key: ZY2YAo3WrW+Eq28oLYVW89mDwst//QLJyqiF4TMP+Vg
  endpoint: https://bookstore-bucket.sgp1.digitaloceanspaces.com
  bucket-name: bookstore-bucket