# Custom properties to ease configuration overrides
# on command-line or IDE launch configurations
schema: http
hostname: localhost
reverse-proxy-port: 9000
vue-port: 9200
vue-prefix: /vue-ui
vue-uri: ${schema}://${hostname}:${vue-port}${vue-prefix}
authorization-server-port: 8080
authorization-server-prefix: /auth
authorization-server-uri: ${schema}://${hostname}:${authorization-server-port}${authorization-server-prefix}
bff-port: 9001
bff-prefix: /bff
bff-uri: ${schema}://${hostname}:${bff-port}

server:
  port: ${reverse-proxy-port}
  ssl:
    enabled: false

spring:
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      routes:
        # Vue UI
        - id: vue-ui
          uri: ${vue-uri}
          predicates:
            - Path=${vue-prefix}/**

        # Authorization Server
        - id: authorization-server
          uri: ${authorization-server-uri}
          predicates:
            - Path=${authorization-server-prefix}/**

        # BFF
        - id: bff
          uri: ${bff-uri}
          predicates:
            - Path=${bff-prefix}/**
          filters:
            - StripPrefix=1
  application:
    name: reverse-proxy