server:
  port: 7081

spring:
  application:
    name: edge-service
  cloud:
    gateway:
      routes:
        - id: lms
          uri: ${LMS_URI:http://localhost:7084}
          predicates:
            - Path=/api/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            - TokenRelay=
            - SaveSession
            - StripPrefix=1
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/e-learning-project
        registration:
          bff-service:
            provider: keycloak
            authorization-grant-type: authorization_code
            client-id: bff-service-confidential
            client-secret: ${KEYCLOAK_CLIENT_SECRET:secret}
            scope: openid,profile,email,offline_access

com:
  c4-soft:
    springaddons:
      oidc:
        ops:
          - iss: http://localhost:8080/realms/e-learning-project
            authorities:
              - path: .roles
            aud:
        client:
          client-uri: http://localhost:7081
          security-matchers:
            - /api/**
            - /login/**
            - /oauth2/**
            - /logout/**
          permit-all:
            - /api/**
            - /login/**
            - /oauth2/**
            - /logout/connect/back-channel/bff-service
          post-logout-redirect-host: localhost
          csrf: cookie_accessible_from_js
          oauth2-redirections:
            rp-initiated-logout: accepted
          back-channel-logout:
            enabled: true
            # internal-logout-uri: ${reverse-proxy-uri}${bff-prefix}/logout
            # should work too, but there is no reason to go through the reverse proxy for this internal call
        # SecurityFilterChain with oauth2ResourceServer() (sessions and CSRF protection disabled)
        resourceserver:
          permit-all:
            - /login-options
            - /error
            - /actuator/health/readiness
            - /actuator/health/liveness

management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: gateway, health, info