client-uri: http://localhost:7081

server:
  port: 7081

spring:
  application:
    name: bff
  cloud:
    gateway:
      routes:
        - id: lms
          uri: ${LMS_SERVICE_URI:http://localhost:7084}
          predicates:
            - Path=/api/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            - TokenRelay
            - SaveSession
            - StripPrefix=1
        - id: angular
          uri: ${ANGULAR_URI:http://localhost:4200}
          predicates:
            - Path=/,/*.css,/*.js,/favicon.ico,/angular-ui/**
  security:
    oauth2:
      client:
        provider:
          keycloak101:
            issuer-uri: http://localhost:8080/realms/keycloak101
        registration:
          keycloak101:
            provider: keycloak101
            authorization-grant-type: authorization_code
            client-id: bff-client
            client-secret: secret
            scope: openid,profile,email,offline_access

management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: gateway, health, info
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

bff:
  greeting: Welcome to BFF from local!