apiVersion: apps/v1
kind: Deployment
metadata:
  name: lms
  labels:
    app: lms
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lms
  template:
    metadata:
      labels:
        app: lms
    spec:
      containers:
        - name: lms
          image: lms
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                command: [ "sh", "-c", "sleep 5" ]
          ports:
            - containerPort: 7084
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 7084
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 7084
            initialDelaySeconds: 5
            periodSeconds: 15
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://el-postgres/lms