name: Resource server CI with Gradle

on:
  push:
    paths:
      - 'resource-server/**'
      - 'edge-service/**'
    branches: [ main ]
  pull_request:
    branches: [ main ]
    paths:
      - 'resource-server/**'
      - 'edge-service/**'

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'gradle'

      - name: Build with Gradle
        run: |
          cd resource-server
          ./gradlew build